apiVersion: v1
kind: ConfigMap
metadata:
  name: bind9-config
  namespace: infra
data:
  named.conf.local: |
    zone "lab.local" {
        type master;
        file "/etc/bind/zones/db.lab.local";
    };
    zone "2.0.192.in-addr.arpa" {
        type master;
        file "/etc/bind/zones/db.192.0.2";
    };
  db.lab.local: |
    $TTL    604800
    @       IN      SOA     dns-server.lab.local. admin.lab.local. (
                                  2024040302         ; Serial
                             604800         ; Refresh
                              86400         ; Retry
                            2419200         ; Expire
                             604800 )       ; Negative Cache TTL
    @       IN      NS      dns-server.lab.local.
    dns-server      IN      A       192.0.2.x
    k8s-master      IN      A       192.0.2.10
    k8s-worker-01   IN      A       192.0.2.11
    k8s-worker-02   IN      A       192.0.2.12
    hypervisor-01           IN      A       192.0.2.1
    hypervisor-02           IN      A       192.0.2.2
    grafana         IN      A       192.0.2.10
    prometheus      IN      A       192.0.2.10
    zabbix          IN      A       192.0.2.10
    argocd          IN      A       192.0.2.10
  db.192.0.2: |
    $TTL    604800
    @       IN      SOA     dns-server.lab.local. admin.lab.local. (
                                  2024040301         ; Serial
                             604800         ; Refresh
                              86400         ; Retry
                            2419200         ; Expire
                             604800 )       ; Negative Cache TTL
    @       IN      NS      dns-server.lab.local.
    143     IN      PTR     dns-server.lab.local.
    95      IN      PTR     hypervisor-01.lab.local.
    96      IN      PTR     hypervisor-02.lab.local.
    140     IN      PTR     k8s-master.lab.local.
    141     IN      PTR     k8s-worker-01.lab.local.
    142     IN      PTR     k8s-worker-02.lab.local.
