[master]
k8s-master ansible_host=192.0.2.10

[workers]
k8s-worker-01 ansible_host=192.0.2.11
k8s-worker-02 ansible_host=192.0.2.12

[k3s_cluster:children]
master
workers

[k3s_cluster:vars]
ansible_user=devops
ansible_become=yes
